version: '3.8'

services:
  auth_backend:
    container_name: auth_backend
    build:
      context: ./backend/auth
    command: gunicorn auth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/auth:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
    name: pgdata
  pgadmin_data:
    name: pgadmin_data
