version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - api

  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - api
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_SERVICE=db
      - DB_PORT=5432

volumes:
  postgres_data:

networks:
  api:
