
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - auth-backend
      - games-backend
      - tournaments-backend
      - users-backend
      - chat-backend

  auth-backend:
    container_name: auth-backend
    build:
      context: ./backend/auth
    command: gunicorn auth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/auth:/app
    networks:
      - backend
      - database
    depends_on:
      - db
    env_file:
      - .env

  games-backend:
    container_name: games-backend
    build:
      context: ./backend/games
    command: gunicorn games.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/games:/app
    networks:
      - backend
      - database
    depends_on:
      - db
    env_file:
      - .env

  tournaments-backend:
    container_name: tournaments-backend
    build:
      context: ./backend/tournaments
    command: gunicorn tournaments.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/tournaments:/app
    networks:
      - backend
      - database
    depends_on:
      - db
    env_file:
      - .env

  users-backend:
    container_name: users-backend
    build:
      context: ./backend/users
    command: gunicorn users.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/users:/app
    networks:
      - backend
      - database
    depends_on:
      - db
    env_file:
      - .env

  chat-backend:
    container_name: chat-backend
    build:
      context: ./backend/chat
      dockerfile: Dockerfile
    volumes:
      - ./backend/chat:/app
    networks:
      - backend
      - database
      - redis
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - database
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./postgres/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - database
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
  database:
    name: db
    driver: bridge
  redis:
    name: redis

volumes:
  pgdata:
    name: pgdata
  pgadmin_data:
    name: pgadmin_data
